### ISSUE TITLE
`Main` snippet arguments

### ISSUE THREAD

**Issue by clembu** [oooreadooo/HdsCppSnippets#1]
Hi.

Your main snippet has a name error.
```c
void main(int argc,char argc[])
{
    
}
```

`argc` is used twice.

Should be
```c
void main(int argc,char argv[])
{
    
}
```

**Comment by agubarev** [comment]
idd, please fix the typo in main snippet:

mai          void main(int argc,char argc[]){}
main         void main(int argc,char argc[]){}


argv[], not argc[]

**Comment by chenjr15** [comment]
`void main(int argc,char argc[]) ` should be `int  main(int argc,char* argv[])` 
返回值应该是int,第二个参数类型应该是char**
